import { NextRequest,NextResponse } from 'next/server';
import { getSupabase } from '../../../lib/marketing/supabase';
import { getAuthContext,unauthorized } from '../../../lib/auth'; import { archivedListingResponse, getActiveListing } from '../../../lib/catalog/active-listing';
import { buildSellerExport } from '../../../lib/catalog/contracts';
export const runtime='nodejs';
async function load(req:NextRequest){const auth=getAuthContext(req);if(!auth)return {error:NextResponse.json(unauthorized(),{status:401})};const sku=req.nextUrl.searchParams.get('sku');if(!sku)return {error:NextResponse.json({error:'SKU obrigatório.'},{status:400})};const db=getSupabase();if(!db)return {error:NextResponse.json({error:'Supabase não configurado.'},{status:503})};const active=await getActiveListing(db,auth,sku);if(active.error)throw active.error;if(active.archived)return {error:NextResponse.json(archivedListingResponse(),{status:404})};if(!active.listing)return {error:NextResponse.json({error:'SKU não encontrado.'},{status:404})};return {auth,db,data:active.listing};}
function makeExport(data:any){return buildSellerExport({...data.payload,sku:data.sku,title:data.title,brand:data.brand,template_key:data.template_key||(data.payload||{}).template_key,template_version:data.template_version||(data.payload||{}).template_version,human_reviewed:data.human_reviewed});}
export async function GET(req:NextRequest){try{const loaded=await load(req);if('error'in loaded)return loaded.error;let exported;try{exported=makeExport(loaded.data)}catch(e){return NextResponse.json({error:'Export bloqueado: dados inválidos.',errors:String(e instanceof Error?e.message:e).split(',')},{status:422})}return new NextResponse(JSON.stringify(exported.json,null,2),{headers:{'content-type':'application/json','content-disposition':`attachment; filename="seller-handoff-${loaded.data.sku}.json"`}})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Falha ao exportar.'},{status:500})}}
export async function POST(req:NextRequest){try{const loaded=await load(req);if('error'in loaded)return loaded.error;let exported;try{exported=makeExport(loaded.data)}catch(e){return NextResponse.json({error:'Export bloqueado: dados inválidos.',errors:String(e instanceof Error?e.message:e).split(',')},{status:422})}const {data,error}=await loaded.db.from('prelistings').update({status:'exported',updated_at:new Date().toISOString()}).eq('id',loaded.data.id).eq('organization_id',loaded.auth.organizationId).eq('owner_id',loaded.auth.userId).neq('status','archived').select('id,sku,status,updated_at').single();if(error)throw error;if(data.status!=='exported')throw new Error('Readback do Seller Handoff não confirmou exportação.');return NextResponse.json({data,export:exported.json},{status:201})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Falha ao registrar exportação.'},{status:500})}}
