import {NextRequest,NextResponse} from 'next/server';
import {resolveAuthContext,unauthorized} from '../../../../lib/auth';
import {getSupabase} from '../../../../lib/marketing/supabase';
import {listMarketplaceAccounts,saveMarketplaceAccount,recordCredentialIncident,CREDENTIAL_CODES} from '../../../../lib/marketplaces/account-registry';
import {readJsonBody,RequestBodyError} from '../../../../lib/http';
import {CatalogError} from '../../../../lib/catalog/repository';
import {traceRequest} from '../../../../lib/operations/trace';
export function GET(req:NextRequest){return traceRequest('api.catalog.accounts',async()=>{const auth=await resolveAuthContext(req);if(!auth)return NextResponse.json(unauthorized(),{status:401});const db=getSupabase();if(!db)return NextResponse.json({error:'Supabase indisponível.'},{status:503});try{return NextResponse.json({data:await listMarketplaceAccounts(db,auth)});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Falha ao listar contas.'},{status:error instanceof CatalogError?error.status:503});}});}
export function POST(req:NextRequest){return traceRequest('api.catalog.accounts',async()=>{const auth=await resolveAuthContext(req);if(!auth)return NextResponse.json(unauthorized(),{status:401});const db=getSupabase();if(!db)return NextResponse.json({error:'Supabase indisponível.'},{status:503});try{return NextResponse.json({data:await saveMarketplaceAccount(db,auth,await readJsonBody(req,12000))},{status:201});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Falha ao salvar conta.'},{status:error instanceof CatalogError||error instanceof RequestBodyError?error.status:503});}});}
export function PATCH(req:NextRequest){return traceRequest('api.catalog.accounts',async()=>{const auth=await resolveAuthContext(req);if(!auth)return NextResponse.json(unauthorized(),{status:401});const db=getSupabase();if(!db)return NextResponse.json({error:'Supabase indisponível.'},{status:503});try{const body=await readJsonBody(req,12000);if(typeof body.account_id!=='string'||!CREDENTIAL_CODES.includes(body.code))return NextResponse.json({error:'Conta e código de credencial são obrigatórios.'},{status:400});return NextResponse.json({data:await recordCredentialIncident(db,auth,body.account_id,body.code,String(body.message||'Falha de credencial.'),body.evidence&&typeof body.evidence==='object'?body.evidence:{})},{status:201});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Falha ao registrar credencial.'},{status:error instanceof CatalogError||error instanceof RequestBodyError?error.status:503});}});}
