'use client';
import ArchivePanel from '../ArchivePanel';
import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import { api, download } from '../../../lib/catalog/client';
import { CHANNELS, CHANNEL_LABELS, type Channel } from '../../../lib/catalog/channels';
import type { Issue, ProductInput } from '../../../lib/catalog/model';
import SchemaEditor from '../SchemaEditor';
import AssetPanel from '../AssetPanel';
import ChannelCopyEditor from '../ChannelCopyEditor';
import EbayOperations from '../EbayOperations';
import { CAPABILITIES } from '../../../lib/marketplaces/capabilities';

const fields = { mpn:'MPN comprovado',ebay_condition:'Condição eBay (NEW)',ebay_location:'Localização eBay (merchantLocationKey)',ebay_payment_policy:'eBay Payment Policy ID',ebay_return_policy:'eBay Return Policy ID',ebay_fulfillment_policy:'eBay Fulfillment Policy ID',title: 'Título', brand: 'Marca', manufacturer: 'Fabricante', origin: 'País de origem', material: 'Material', color: 'Cor', included: 'Itens inclusos', pkg_length: 'Comprimento da embalagem (in)', pkg_width: 'Largura da embalagem (in)', pkg_height: 'Altura da embalagem (in)', pkg_weight: 'Peso da embalagem (lb)', gtin: 'GTIN / UPC / EAN', asin: 'ASIN existente', price: 'Preço (USD)', qty: 'Estoque', handling: 'Prazo de produção/envio (dias)', parent_sku: 'SKU pai', variation: 'Tema de variação', compliance: 'Documentação de segurança / certificações' };
export default function Editor({ sku, initialChannel = 'amazon-us' }: { sku: string; initialChannel?: Channel }) {
  const [ebayEnabled,setEbayEnabled]=useState(false),[canPublish,setCanPublish]=useState(false);
  const [copy,setCopy]=useState({locale:'en_US' as const,title:'',bullets:'',description:'',keywords:''});const [copyDirty,setCopyDirty]=useState(false);
  const [channel, setChannel] = useState<Channel>(initialChannel); const [product, setProduct] = useState<ProductInput | null>(null); const [version, setVersion] = useState(''); const [contentHash, setContentHash] = useState('');
  const [report, setReport] = useState<{ ready: boolean; issues: Issue[] } | null>(null); const [busy, setBusy] = useState(false); const [dirty, setDirty] = useState(false); const [message, setMessage] = useState('');
  const [baselineAttributes, setBaselineAttributes] = useState<Record<string, unknown>>({}); const [attributes, setAttributes] = useState<Record<string, unknown>>({}); const [kind, setKind] = useState('unknown'); const [productType, setProductType] = useState(''); const [category, setCategory] = useState(''); const [source, setSource] = useState(''); const [facts, setFacts] = useState<string[]>([]); const [output, setOutput] = useState<unknown>(null); const [configDirty, setConfigDirty] = useState(false); const [attrsDirty, setAttrsDirty] = useState(false); const [resolution, setResolution] = useState(''); const [sourceFields, setSourceFields] = useState<string[]>([]); const [publication, setPublication] = useState(false); const [canReview,setCanReview]=useState(false);
  const load = useCallback(async () => { const data = await api(`/api/catalog/item?sku=${encodeURIComponent(sku)}&channel=${channel}`); setProduct(data.product);const currentCopy=data.product._catalog?.channels[channel]?.copy;setCopy({locale:'en_US',title:String(currentCopy?.title??data.product.title??''),bullets:String(currentCopy?.bullets??data.product.bullets??''),description:String(currentCopy?.description??data.product.description??''),keywords:String(currentCopy?.keywords??data.product.keywords??'')});setCopyDirty(false); setVersion(data.updated_at); setContentHash(data.content_hash); setReport(data.report); setAttributes(data.effective_attributes); setBaselineAttributes(data.effective_attributes); setKind(data.product._catalog?.kind || 'unknown'); setProductType(data.product._catalog?.channels[channel]?.product_type || ''); setCategory(data.product._catalog?.channels[channel]?.category || ''); setDirty(false); setConfigDirty(false); setAttrsDirty(false); const status=await api('/api/catalog/status'); setPublication(status.publication && status.permissions.publish);setCanReview(status.permissions.review);setCanPublish(status.permissions.publish);setEbayEnabled(status.ebay_publication); }, [sku, channel]);
  const run = async (task: () => Promise<void>) => { setBusy(true); setMessage(''); try { await task(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Falha na operação.'); } finally { setBusy(false); } };
  useEffect(() => { void run(load); }, [load]);
  const action = async (name: string, extra: Record<string, unknown> = {}) => { const data = await api('/api/catalog/actions', { sku, channel, action: name, updated_at: version, ...extra }); setOutput(data.output || null); await load(); return data; };
  const save = async () => {
    let currentVersion = version;
    if (dirty) {
      const response = await fetch('/api/listings', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ sku, updated_at: currentVersion, payload: product }) });
      const data = await response.json(); if (!response.ok) throw new Error(data.error); currentVersion = data.data.updated_at;
    }
    if (configDirty || attrsDirty || copyDirty) {
      const current = await api(`/api/catalog/item?sku=${encodeURIComponent(sku)}&channel=${channel}`);
      if (current.updated_at !== currentVersion) throw new Error('O produto mudou. Recarregue antes de salvar os atributos.');
      // Unedited derived fields follow the saved product, even when several areas were edited.
      const previousAttributes = baselineAttributes;
      const overrides = { ...product?._catalog?.channels[channel]?.attributes };
      for (const key of Object.keys(previousAttributes)) if (!(key in attributes)) delete overrides[key];
      for (const [key, value] of Object.entries(attributes)) if (JSON.stringify(value) !== JSON.stringify(previousAttributes[key])) overrides[key] = value;
      await api('/api/catalog/actions', { sku, channel, action: 'configure', updated_at: currentVersion, ...(configDirty ? { kind, product_type: productType, category } : {}), ...(attrsDirty ? { attributes: overrides } : {}),...(copyDirty?{copy}:{}) });
    }
    await load(); setMessage('Alterações salvas. Revise a versão atual antes de exportar.');
  };
  const set = (key: string, value: unknown) => { setProduct(current => current && ({ ...current, [key]: value })); setDirty(true); };
  if (!product) return <main className="max-w-5xl mx-auto p-8"><Link href="/catalog">← Catálogo</Link><p role="alert" className="mt-5">{message || 'Carregando produto…'}</p></main>;
  const listing = product._catalog?.channels[channel]; const unsaved = dirty || configDirty || attrsDirty || copyDirty;
  return <main className="mx-auto max-w-6xl p-6 md:p-10"><header className="flex flex-wrap justify-between gap-4"><div><Link className="text-blue-600" href="/catalog">← Catálogo</Link><Link className="text-blue-600 ml-4" href={`/marketing/${encodeURIComponent(sku)}`}>Economia e marketing</Link><h1 className="text-3xl font-black mt-3">{sku}</h1><p className="text-slate-500">{String(product.title)}</p></div><div className="flex items-start gap-2"><select disabled={unsaved || busy} className="border rounded p-2" value={channel} onChange={event => setChannel(event.target.value as Channel)}>{CHANNELS.map(value => <option key={value} value={value}>{CHANNEL_LABELS[value]}</option>)}</select><button className="btn btn-primary" disabled={busy || !unsaved} onClick={() => run(save)}>Salvar alterações</button></div></header>{message && <p role="alert" className="mt-5 bg-blue-50 text-blue-800 p-4 rounded">{message}</p>}{unsaved && <p className="mt-4 text-amber-700">Há alterações não salvas. Salve antes de executar análises ou trocar de canal.</p>}
    <section className="card mt-5"><h2 className="text-lg font-bold">Pendências · {CHANNEL_LABELS[channel]}</h2><p className="mt-1 text-sm text-slate-500">{report?.ready ? 'Versão aprovada. A exportação verifica novamente todos os requisitos.' : `${report?.issues.length || 0} bloqueios encontrados na versão salva.`}</p><div className="flex flex-wrap gap-2 mt-4">{[['generate', 'Gerar conteúdo'], ['classify', 'Buscar categorias'], ['media', 'Verificar imagens'], ['validate', 'Revalidar'], ['preview', 'Preview Amazon'], ['restrictions', 'Restrições do ASIN'], ['discover', 'Buscar identidade Amazon'], ['fees', 'Estimar tarifas'], ['account-preparation','Consultar policies eBay'], ['history', 'Histórico de versões'], ['monitor', 'Consultar situação'], ['reconcile', 'Reconciliar envio incerto']].map(([name, label]) => <button className="btn" key={name} disabled={busy || unsaved || name==='classify' && !CAPABILITIES[channel].classification || name==='account-preparation' && channel!=='ebay-us' || ['preview', 'restrictions', 'monitor', 'discover', 'fees', 'reconcile'].includes(name) && channel !== 'amazon-us'} onClick={() => run(async () => { if (name==='history') setOutput((await api(`/api/catalog/history?sku=${encodeURIComponent(sku)}`)).data); else await action(name); })}>{label}</button>)}<button className="btn btn-primary" disabled={busy || unsaved || !canReview} onClick={() => run(async () => { await action('review', { expected_hash: contentHash }); setMessage('Versão revisada e aprovada.'); })}>Aprovar esta versão</button><button className="btn" disabled={busy || unsaved || !report?.ready} onClick={() => run(async () => { const data = await api('/api/catalog/actions', { sku, channel, action: 'export' }); download(data.package, `${sku}-${channel}.json`); })}>Exportar pacote</button>{publication && channel === 'amazon-us' && <button className="btn" disabled={busy || unsaved || !report?.ready} onClick={() => run(async () => { if (window.confirm(`Enviar a versão aprovada de ${sku} para a Amazon US?`)) await action('submit', { confirm: true, expected_hash: contentHash }); })}>Enviar à Amazon</button>}</div><div className="mt-4 grid gap-2">{report?.issues.map((issue, index) => <div key={`${issue.code}-${index}`} className="border-l-4 border-amber-400 bg-amber-50 p-3 text-sm"><strong>{issue.field}: {issue.message}</strong><p className="text-slate-600 mt-1">{issue.action}</p></div>)}</div></section>
    <section className="card mt-5"><h2 className="text-lg font-bold">Elegibilidade e classificação</h2><div className="grid gap-4 mt-4 md:grid-cols-3"><label className="field">Natureza da oferta<select className="border rounded p-2" value={kind} onChange={event => { setKind(event.target.value); setConfigDirty(true); }}><option value="unknown">A definir</option><option value="physical">Produto físico</option><option value="custom">Produto personalizado</option><option value="service">Serviço</option></select></label><label className="field">Tipo de produto<input list="product-types" value={productType} onChange={event => { setProductType(event.target.value); setConfigDirty(true); }} /><datalist id="product-types">{listing?.suggestions?.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</datalist></label><label className="field">Categoria / navegação<input value={category} onChange={event => { setCategory(event.target.value); setConfigDirty(true); }} /></label></div><div className="flex gap-2 mt-4"><button className="btn" disabled={busy || dirty || attrsDirty || copyDirty} onClick={() => run(async () => { await action('configure', { kind, product_type: productType, category }); })}>Confirmar classificação</button><button className="btn" disabled={busy || unsaved || !CAPABILITIES[channel].schema || !listing?.product_type || channel !== 'amazon-us' && !listing?.category} onClick={() => run(async () => { await action('schema'); })}>Carregar requisitos oficiais</button></div>{listing?.recommendation && <p className="mt-3 text-sm text-blue-700">Recomendação da IA: {listing.recommendation.id} · confiança {Math.round(listing.recommendation.confidence * 100)}% · {listing.recommendation.reason}. Confirme antes de continuar.</p>}{listing?.suggestions && <p className="mt-3 text-sm text-slate-500">Sugestões: {listing.suggestions.map(item => `${item.name} (${item.id})`).join(' · ')}</p>}</section>
    <ChannelCopyEditor value={copy} busy={busy} channel={CHANNEL_LABELS[channel]} hasSavedCopy={Boolean(listing?.copy)} onChange={value=>{setCopy(value);setCopyDirty(true);}} />
    <section className="card mt-5"><h2 className="text-lg font-bold">Identidade, especificações e oferta</h2><p className="text-sm text-slate-500 mt-2">Os dados abaixo são compartilhados. Textos específicos do canal são preparados na seção acima; sem uma versão específica, o canal usa este conteúdo base.</p><div className="grid gap-4 mt-4 md:grid-cols-3">{Object.entries(fields).filter(([key])=>!key.startsWith('ebay_')||channel==='ebay-us').map(([key, label]) => <label key={key} className="field">{label}<input type={['pkg_length', 'pkg_width', 'pkg_height', 'pkg_weight', 'price', 'qty', 'handling'].includes(key) ? 'number' : 'text'} value={String(product[key] ?? '')} onChange={event => set(key, event.target.value)} /></label>)}<label className="field">Fulfillment<select className="border rounded p-2" value={String(product.fulfillment || '')} onChange={event => set('fulfillment', event.target.value)}><option value="">Selecione</option><option value="FBM">FBM · envio pela empresa</option><option value="FBA">FBA · estoque na Amazon</option></select></label><label className="field">Identificador<select className="border rounded p-2" value={String(product.id_type || 'UPC')} onChange={event => set('id_type', event.target.value)}><option>UPC</option><option>EAN</option><option>GTIN</option></select></label><label className="field">Vínculo<select className="border rounded p-2" value={String(product.relationship || 'Standalone')} onChange={event => set('relationship', event.target.value)}><option>Standalone</option><option>Parent</option><option>Child</option></select></label></div><div className="grid gap-4 mt-4">{[['bullets', 'Bullet points (um por linha)'], ['description', 'Descrição'], ['keywords', 'Termos de pesquisa'], ['images', 'URLs HTTPS de imagens (uma por linha)']].map(([key, label]) => <label className="field" key={key}>{label}<textarea className="border rounded p-3 min-h-24" value={Array.isArray(product[key]) ? (product[key] as string[]).join('\n') : String(product[key] || '')} onChange={event => set(key, event.target.value)} /></label>)}</div><div className="grid gap-3 mt-4 text-sm">{[['gtin_exempt', 'Tenho isenção de GTIN aprovada para esta marca/categoria'], ['assets_reviewed', 'Revisei os direitos, a fidelidade, o fundo e o conteúdo das imagens'], ['policy_reviewed', 'Revisei políticas do canal e documentos de segurança aplicáveis']].map(([key, label]) => <label key={key}><input className="mr-2" type="checkbox" checked={product[key] === true} onChange={event => set(key, event.target.checked)} />{label}</label>)}</div></section>
    <section className="card mt-5"><h2 className="text-lg font-bold">Confirmar fatos técnicos</h2><p className="mt-1 text-sm text-slate-500">Confirme somente os valores que foram verificados em uma fonte confiável. Medidas do produto e da embalagem são diferentes.</p><input aria-label="Fonte da confirmação" className="w-full border rounded p-3 mt-3" placeholder="Ex.: ficha técnica do fabricante, medição da embalagem em 05/10/2026" value={source} onChange={event => setSource(event.target.value)} /><div className="grid gap-2 mt-3 md:grid-cols-3">{['brand', 'manufacturer', 'origin', 'material', 'color', 'included', 'pkg_length', 'pkg_width', 'pkg_height', 'pkg_weight', 'gtin', 'mpn', 'compliance'].map(key => <label className="text-sm" key={key}><input type="checkbox" className="mr-2" checked={facts.includes(key)} onChange={event => setFacts(event.target.checked ? [...facts, key] : facts.filter(field => field !== key))} />{fields[key as keyof typeof fields] || key} · {product._catalog?.facts[key]?.status === 'confirmed' ? 'confirmado' : 'pendente'}</label>)}</div><button className="btn mt-4" disabled={busy || unsaved || !facts.length || !source} onClick={() => run(async () => { await action('confirm-facts', { fields: facts, source }); setFacts([]); })}>Registrar confirmação dos campos selecionados</button></section>
    <section className="card mt-5"><h2 className="text-lg font-bold">Atributos do marketplace</h2>{listing?.schema ? <><p className="text-sm text-slate-500 my-3">Schema {listing.schema.version} · recuperado em {listing.schema.fetched_at}</p><SchemaEditor schema={listing.schema.schema} attributes={attributes} onChange={value => { setAttributes(value); setAttrsDirty(true); }} /><button className="btn mt-4" disabled={busy || dirty || configDirty || copyDirty} onClick={() => run(async () => { await action('configure', { attributes }); })}>Salvar atributos do canal</button></> : <p className="mt-3 text-slate-500">Confirme a classificação e carregue os requisitos oficiais para preencher os atributos.</p>}</section>
    {product._catalog?.variants?.length ? <section className="card mt-5"><h2 className="font-bold">Família de variantes</h2>{product._catalog.variants.map(variant => <p key={variant.sku} className="text-sm mt-2">{variant.sku} · {JSON.stringify(variant.attributes)}</p>)}</section> : null}
    {Boolean(product.source_update) && <section className="card mt-5"><h2 className="font-bold text-amber-700">Alteração detectada na fonte</h2><p className="text-sm mt-2">A loja mudou desde a importação. Compare os dados e revise antes de aplicar ao listing.</p><pre className="overflow-auto text-xs mt-3">{JSON.stringify(product.source_update, null, 2)}</pre><div className="flex flex-wrap gap-3 mt-3">{['title','description','images','price','qty','brand','origin','material','pkg_length','pkg_width','pkg_height','pkg_weight'].map(key => <label key={key} className="text-sm"><input type="checkbox" className="mr-1" checked={sourceFields.includes(key)} onChange={event => setSourceFields(event.target.checked ? [...sourceFields, key] : sourceFields.filter(field => field !== key))} />{key}</label>)}</div><button className="btn mt-3" disabled={busy || unsaved || !sourceFields.length} onClick={() => run(async () => { await action('apply-source-update', { fields: sourceFields }); setSourceFields([]); })}>Aplicar campos selecionados da fonte</button><input aria-label="Motivo para manter os dados" className="w-full border rounded p-3 mt-3" value={resolution} onChange={event => setResolution(event.target.value)} placeholder="Motivo para manter os dados atuais" /><button className="btn mt-3" disabled={busy || unsaved || !resolution.trim()} onClick={() => run(async () => { await action('apply-source-update', { keep_current: true, reason: resolution }); setResolution(''); })}>Manter dados atuais e registrar decisão</button></section>}
    {listing?.submission && <section className="card mt-5"><h2 className="font-bold">Submissão · {listing.submission.status}</h2><p className="text-sm mt-2">Situação da oferta: {listing.submission.publication_status}</p></section>}
    {output !== null && <details className="card mt-5"><summary className="font-bold cursor-pointer">Resultado da última operação</summary><pre className="mt-3 text-xs whitespace-pre-wrap break-all">{JSON.stringify(output, null, 2)}</pre></details>}
    {channel==='ebay-us'&&<EbayOperations sku={sku} busy={busy} unsaved={unsaved} canPublish={canPublish} enabled={ebayEnabled} run={run} reload={load} />}
    <AssetPanel sku={sku} busy={busy} run={run} /><ArchivePanel sku={sku} version={version} disabled={busy||unsaved} canArchive={canPublish}/>
  </main>;
}
