'use client';
import {useEffect,useState} from 'react';
export default function AmazonFeeEconomics({sku,productVersion,profileVersion,disabled,onRefresh}:{sku:string;productVersion:string;profileVersion:string;disabled:boolean;onRefresh:()=>Promise<void>}){
 const [report,setReport]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{setReport(null);setError('');},[sku,productVersion,profileVersion,disabled]);
 async function inspect(refresh=false){setBusy(true);setError('');setReport(null);try{
  if(refresh){const response=await fetch('/api/catalog/actions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sku,action:'fees',channel:'amazon-us',updated_at:productVersion})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Consulta de tarifas falhou.');await onRefresh();}
  const response=await fetch('/api/marketing-economics?sku='+encodeURIComponent(sku));const result=await response.json();if(!response.ok)throw new Error(result.error||'Projeção indisponível.');setReport(result.data);
 }catch(error){setError(error instanceof Error?error.message:'Falha ao consultar.');}finally{setBusy(false);}}
 return <section className="card"><h2 className="font-bold text-lg">Projeção com tarifas estimadas Amazon</h2><p className="text-sm text-slate-500 mt-2">Compara os custos de operação informados com a estimativa da Amazon para a conta, identidade, preço, frete cobrado e fulfillment atuais. Os custos salvos e a aprovação formal permanecem sujeitos à revisão.</p><div className="flex gap-2 mt-3"><button className="btn" disabled={busy||disabled} onClick={()=>inspect()}>Conferir estimativa registrada</button><button className="btn" disabled={busy||disabled} onClick={()=>inspect(true)}>Consultar Product Fees</button></div>{error&&<p role="alert" className="text-amber-700 mt-3">{error}</p>}{report&&<div className="mt-4"><p className="font-bold">ESTIMATIVA · USD {report.fee_estimate.total_fees.toFixed(2)} em tarifas Amazon</p><p className="text-xs mt-2">Preço USD {report.fee_estimate.target.price} + frete cobrado USD {report.fee_estimate.target.shipping_charge} · {report.fee_estimate.target.fulfillment} · {report.fee_estimate.estimated_at} · vence {report.fee_estimate.expires_at}</p>{report.estimated_margin&&<p className="mt-3">Margem projetada: {report.estimated_margin.percentage}% · lucro USD {report.estimated_margin.profit.toFixed(2)}. Usa o total estimado Amazon uma vez e os custos de operação, sem somar novamente as taxas manuais.</p>}{report.blockers.map((blocker:string)=><p role="alert" className="text-amber-700 mt-2" key={blocker}>{blocker}</p>)}<p className="text-xs mt-3">Projeção consultiva. Não substitui os custos confirmados ou uma fatura real, nem altera o perfil automaticamente.</p><details className="mt-3"><summary>Identidade, valores e fonte da projeção</summary><pre className="overflow-auto text-xs max-h-80">{JSON.stringify(report,null,2)}</pre></details></div>}</section>;
}
