'use client';
import {useEffect,useId,useRef,useState} from 'react';
import {REQUIRED_COST_FIELDS,type CostField} from '../../lib/marketing/margin';
import {isNumericInput} from '../../lib/catalog/numeric-input';
const labels:Record<CostField,string>={product_cost:'Produto',printing_cost:'Impressão',packaging_cost:'Embalagem',shipping_cost:'Frete',amazon_referral_fee:'Comissão Amazon',fulfillment_fee:'Fulfillment',other_costs:'Outros custos'};
export default function MarketingEconomicsEditor({sku,costs,profileVersion,onSaved,onDirty}:{sku:string;costs:any;profileVersion:string|null;onSaved:()=>Promise<void>;onDirty:(dirty:boolean)=>void}){
 const [values,setValues]=useState<Record<string,string>>({}),[source,setSource]=useState(''),[date,setDate]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [failed,setFailed]=useState(false),id=useId(),pending=useRef(false),messageRef=useRef<HTMLParagraphElement>(null),currentSku=useRef(sku);currentSku.current=sku;
 const original=JSON.stringify(costs||{});
 useEffect(()=>{const input=JSON.parse(original);setValues(Object.fromEntries(REQUIRED_COST_FIELDS.map(field=>[field,input[field]===undefined||input[field]===null?'':String(input[field])])));setSource(String(input.source||''));const instant=new Date(typeof input.calculated_at==='string'&&input.calculated_at?input.calculated_at:NaN);setDate(Number.isFinite(instant.getTime())?new Date(instant.getTime()-instant.getTimezoneOffset()*60000).toISOString().slice(0,16):'');setMessage('');setFailed(false);onDirty(false);},[sku,original,onDirty]);
 useEffect(()=>{if(failed)messageRef.current?.focus();},[failed,message]);
 const valid=REQUIRED_COST_FIELDS.every(field=>isNumericInput(values[field])&&Number(values[field])>=0)&&Boolean(source.trim())&&Number.isFinite(Date.parse(date));
 async function save(){if(!valid||pending.current)return;pending.current=true;setBusy(true);setMessage('');setFailed(false);try{
  const response=await fetch('/api/marketing-profiles',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sku,status:'draft',expected_profile_version:profileVersion,costs:{...Object.fromEntries(REQUIRED_COST_FIELDS.map(field=>[field,Number(values[field])])),currency:'USD',source:source.trim(),calculated_at:new Date(date).toISOString()}})});
  const result=await response.json();if(!response.ok)throw new Error(response.status===409?`${result.error||'Esta versão mudou.'} Recarregue o perfil e confira os custos antes de salvar novamente.`:result.error||'Falha ao salvar custos.');if(currentSku.current!==sku)return;await onSaved();if(currentSku.current===sku)setMessage('Custos salvos. Revise esta nova versão antes de aprovar.');
 }catch(error){if(currentSku.current===sku){setFailed(true);setMessage(error instanceof Error?error.message:'Falha ao salvar.');}}finally{pending.current=false;setBusy(false);}}
 return <section className="card" aria-busy={busy} aria-labelledby={`${id}-heading`}><h2 id={`${id}-heading`} className="text-lg font-bold">Custos unitários · USD</h2><p id={`${id}-help`} className="mt-2 text-sm text-slate-500">Informe todos os valores, a fonte e a data da apuração. Zero precisa ser confirmado; campos vazios não são estimados. O preço de venda vem do catálogo.</p><div className="field-grid mt-4">{REQUIRED_COST_FIELDS.map(field=><label key={field} className="field" htmlFor={`${id}-${field}`}>{labels[field]}<input id={`${id}-${field}`} aria-describedby={`${id}-help`} required type="number" min="0" step="0.01" disabled={busy} value={values[field]??''} onChange={event=>{setValues({...values,[field]:event.target.value});onDirty(true);}}/></label>)}<label className="field" htmlFor={`${id}-source`}>Fonte dos custos<input id={`${id}-source`} required disabled={busy} maxLength={1000} value={source} onChange={event=>{setSource(event.target.value);onDirty(true);}} placeholder="Ficha, orçamento ou relatório conferido"/></label><label className="field" htmlFor={`${id}-date`}>Data e hora da apuração<input id={`${id}-date`} required disabled={busy} type="datetime-local" value={date} onChange={event=>{setDate(event.target.value);onDirty(true);}}/></label></div><p role="status" aria-live="polite" className="text-sm mt-3">{busy?'Salvando custos e recalculando margem…':!valid?'Preencha os sete custos, a fonte e a data para habilitar o salvamento.':''}</p><button type="button" className="btn btn-primary mt-4" disabled={busy||!valid} onClick={save}>{busy?'Salvando…':'Salvar custos e calcular margem'}</button>{message&&<p ref={messageRef} tabIndex={failed?-1:undefined} role={failed?'alert':'status'} className="mt-3 text-sm">{message}</p>}</section>;
}
