'use client';
import {useEffect,useState} from 'react';
import {REQUIRED_COST_FIELDS,type CostField} from '../../lib/marketing/margin';
const labels:Record<CostField,string>={product_cost:'Produto',printing_cost:'Impressão',packaging_cost:'Embalagem',shipping_cost:'Frete',amazon_referral_fee:'Comissão Amazon',fulfillment_fee:'Fulfillment',other_costs:'Outros custos'};
export default function MarketingEconomicsEditor({sku,costs,profileVersion,onSaved,onDirty}:{sku:string;costs:any;profileVersion:string|null;onSaved:()=>Promise<void>;onDirty:(dirty:boolean)=>void}){
 const [values,setValues]=useState<Record<string,string>>({}),[source,setSource]=useState(''),[date,setDate]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const original=JSON.stringify(costs||{});
 useEffect(()=>{const input=JSON.parse(original);setValues(Object.fromEntries(REQUIRED_COST_FIELDS.map(field=>[field,input[field]===undefined?'':String(input[field])])));setSource(String(input.source||''));const instant=new Date(input.calculated_at);setDate(Number.isFinite(instant.getTime())?new Date(instant.getTime()-instant.getTimezoneOffset()*60000).toISOString().slice(0,16):'');onDirty(false);},[original,onDirty]);
 const valid=REQUIRED_COST_FIELDS.every(field=>values[field]!==''&&values[field]!==undefined&&Number.isFinite(Number(values[field]))&&Number(values[field])>=0)&&source.trim()&&date;
 async function save(){setBusy(true);setMessage('');try{
  const response=await fetch('/api/marketing-profiles',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sku,status:'draft',expected_profile_version:profileVersion,costs:{...Object.fromEntries(REQUIRED_COST_FIELDS.map(field=>[field,Number(values[field])])),currency:'USD',source:source.trim(),calculated_at:new Date(date).toISOString()}})});
  const result=await response.json();if(!response.ok)throw new Error(result.error||'Falha ao salvar custos.');await onSaved();setMessage('Custos salvos. Revise esta nova versão antes de aprovar.');
 }catch(error){setMessage(error instanceof Error?error.message:'Falha ao salvar.');}finally{setBusy(false);}}
 return <section className="card"><h2 className="text-lg font-bold">Custos unitários · USD</h2><p className="mt-2 text-sm text-slate-500">Informe todos os valores, a fonte e a data da apuração. Zero precisa ser confirmado; campos vazios não são estimados. O preço de venda vem do catálogo.</p><div className="field-grid mt-4">{REQUIRED_COST_FIELDS.map(field=><label key={field} className="field">{labels[field]}<input type="number" min="0" step="0.01" disabled={busy} value={values[field]??''} onChange={event=>{setValues({...values,[field]:event.target.value});onDirty(true);}}/></label>)}<label className="field">Fonte dos custos<input disabled={busy} maxLength={1000} value={source} onChange={event=>{setSource(event.target.value);onDirty(true);}} placeholder="Ficha, orçamento ou relatório conferido"/></label><label className="field">Data e hora da apuração<input disabled={busy} type="datetime-local" value={date} onChange={event=>{setDate(event.target.value);onDirty(true);}}/></label></div><button className="btn btn-primary mt-4" disabled={busy||!valid} onClick={save}>{busy?'Salvando…':'Salvar custos e calcular margem'}</button>{message&&<p role="status" className="mt-3 text-sm">{message}</p>}</section>;
}
