'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
type Profile={sku:string;status:string;economics?:{margin?:{percentage?:number}};audience?:{business_manager_id?:string}};
export default function MarketingPage(){
 const [rows,setRows]=useState<Profile[]>([]),[offset,setOffset]=useState(0),[total,setTotal]=useState(0),[error,setError]=useState(''),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0);
 const pageSize=20;
 useEffect(()=>{
  const abort=new AbortController();let active=true;setLoading(true);setError('');setRows([]);
  fetch('/api/marketing-profiles?offset='+offset,{signal:abort.signal}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||'Não foi possível carregar os perfis.');if(!Array.isArray(data.data))throw new Error('Resposta de perfis inválida.');if(active){setRows(data.data);setTotal(data.total||0);}}).catch(error=>{if(active)setError(error instanceof Error?error.message:'Falha ao carregar perfis.');}).finally(()=>{if(active)setLoading(false);});
  return()=>{active=false;abort.abort();};
 },[offset,retry]);
 return <div className="app-shell"><aside className="sidebar"><div className="mb-8 text-xl font-black text-white">FBRSigns · Marketing</div><Link href="/dashboard" className="block px-3 py-2.5 text-sm text-slate-400">← Catálogo</Link><div className="rounded-lg bg-slate-800 px-3 py-2.5 text-sm text-white" aria-current="page">▣ Marketing readiness</div></aside><main className="main"><header className="mb-7"><div className="text-[11px] font-extrabold uppercase tracking-[.14em] text-blue-600">MP-001 · planos revisáveis</div><h1 className="mb-1 mt-1 text-3xl font-black">Marketing readiness</h1><p className="text-slate-500">Margem real, Amazon PPC, Meta Ads, tracking e launch gate por SKU</p><Link href="/dashboard" className="text-blue-600 inline-block mt-3">← Voltar ao catálogo</Link></header><div className="card" aria-busy={loading}><p role="status" aria-live="polite" className="text-sm text-slate-500">{loading?'Carregando perfis de marketing…':!error&&rows.length?`${offset+1}–${offset+rows.length} de ${total} perfis`:''}</p>{error?<div role="alert" className="my-4 text-sm text-amber-700"><p>{error}</p><button type="button" className="btn mt-3" onClick={()=>setRetry(value=>value+1)}>Tentar carregar novamente</button></div>:!loading&&rows.length===0?<div className="py-10 text-center text-sm text-slate-500">Nenhum perfil encontrado. Abra Economia e marketing no produto para informar os custos.</div>:!loading?<div className="overflow-x-auto"><table className="w-full text-left text-sm"><caption className="text-left py-3 font-semibold">Perfis de marketing por produto</caption><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{['SKU','Status','Margem','Meta BM','Ação'].map(label=><th key={label} scope="col" className="px-4 py-3">{label}</th>)}</tr></thead><tbody className="divide-y">{rows.map(row=><tr key={row.sku}><th scope="row" className="px-4 py-3 font-bold">{row.sku}</th><td className="px-4 py-3">{row.status}</td><td className="px-4 py-3">{row.economics?.margin?.percentage!=null?`${row.economics.margin.percentage}%`:'bloqueada'}</td><td className="px-4 py-3">{row.audience?.business_manager_id||'—'}</td><td className="px-4 py-3"><Link className="text-blue-600 hover:underline" aria-label={`Abrir painel de marketing de ${row.sku}`} href={`/marketing/${encodeURIComponent(row.sku)}`}>Abrir painel</Link></td></tr>)}</tbody></table></div>:null}<nav aria-label="Páginas de perfis de marketing" className="flex flex-wrap gap-3 mt-4"><button type="button" className="btn" disabled={loading||offset===0} onClick={()=>setOffset(value=>Math.max(0,value-pageSize))}>Página anterior</button><button type="button" className="btn" disabled={loading||Boolean(error)||offset+pageSize>=total} onClick={()=>setOffset(value=>value+pageSize)}>Próxima página</button></nav></div></main></div>;
}
