import { readJsonBody,RequestBodyError } from '../../../lib/http';
import { NextRequest, NextResponse } from 'next/server';
import { buildKanbanCards, buildIdempotencyKey } from '../../../lib/marketing/plans';
import { loadMarketingReview } from '../../../lib/marketing/review';
import { validateLaunchReadyTransition } from '../../../lib/marketing/profile-guard';
import { getSupabase } from '../../../lib/marketing/supabase';
import { resolveAuthContext, unauthorized } from '../../../lib/auth';
import { CatalogError } from '../../../lib/catalog/repository';
export const runtime='nodejs';
export async function POST(req:NextRequest){try{const auth=await resolveAuthContext(req);if(!auth)return NextResponse.json(unauthorized(),{status:401});const body=await readJsonBody(req,16384);const sku=String(body?.sku||'');if(!sku)return NextResponse.json({error:'SKU obrigatório.'},{status:400});const cards=buildKanbanCards(sku);if(body.confirm !== true)return NextResponse.json({mode:'dry-run',created:false,cards,warning:'Preview only. Send confirm=true after explicit approval to create cards.'});const db=getSupabase();if(!db)return NextResponse.json({error:'Supabase não configurado.'},{status:503});const review=await loadMarketingReview(db,auth,sku);const profile=review.profile;const transition=validateLaunchReadyTransition(review.gate,review.latestApproval,review.approval_current);if(!transition.ok)return NextResponse.json({error:'Aprovação atual obrigatória.',code:transition.code},{status:400});if(body.expected_hash!==review.content_hash)return NextResponse.json({error:'Revise a versão atual.',code:'REVIEW_VERSION_CHANGED'},{status:409});const key=buildIdempotencyKey(sku,auth.organizationId,review.content_hash);const existing=await db.from('marketing_tasks').select('*').eq('sku',sku).eq('organization_id',auth.organizationId).eq('owner_id',auth.userId).eq('idempotency_key',key);if(existing.error)throw existing.error;if(existing.data?.length===5)return NextResponse.json({mode:'created',created:true,idempotent:true,data:existing.data});const rows=cards.map(card=>({marketing_profile_id:profile.id,sku,agent:card.agent,task_type:card.title,status:'pending',payload:{...card,content_hash:review.content_hash,snapshot:review.snapshot},idempotency_key:key,owner_id:auth.userId,organization_id:auth.organizationId,updated_at:new Date().toISOString()}));const {error}=await db.from('marketing_tasks').upsert(rows,{onConflict:'organization_id,idempotency_key,task_type'});if(error)throw error;const readback=await db.from('marketing_tasks').select('*').eq('sku',sku).eq('organization_id',auth.organizationId).eq('owner_id',auth.userId).eq('idempotency_key',key);if(readback.error)throw readback.error;if(readback.data?.length!==5)throw new Error('Readback Kanban incompleto.');return NextResponse.json({mode:'created',created:true,idempotent:false,data:readback.data});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Falha no Kanban.'},{status:e instanceof CatalogError||e instanceof RequestBodyError?e.status:500});}}
