'use client';
import {useState} from 'react';
import {api} from '../../lib/catalog/client';
export default function ArchivedCatalog({onRestored}:{onRestored:()=>Promise<void>}){
 const [data,setData]=useState<any>(null),[selected,setSelected]=useState<any>(null),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(offset=0){setBusy(true);setError('');try{setData(await api('/api/catalog/archive?offset='+offset));setSelected(null);setConfirmed(false);}catch(error){setError(error instanceof Error?error.message:'Falha ao consultar.');}finally{setBusy(false);}}
 async function restore(){setBusy(true);setError('');try{await api('/api/catalog/archive',{sku:selected.sku,expected_version:selected.updated_at,archive:false,confirm:confirmed,reason});setSelected(null);setConfirmed(false);setReason('');await onRestored();await load(data.offset);}catch(error){setError(error instanceof Error?error.message:'Falha ao restaurar.');}finally{setBusy(false);}}
 return <section className="card mt-5"><h2 className="font-bold text-lg">Preparações arquivadas</h2><button className="btn mt-3" disabled={busy} onClick={()=>load()}>Consultar arquivados</button>{error&&<p role="alert" className="text-red-700 mt-3">{error}</p>}{data&&<><p className="text-sm mt-3">{data.total} produtos arquivados</p>{data.data.map((row:any)=><div key={row.sku} className="border-t py-3 mt-2"><p><b>{row.sku}</b> · {row.title}</p><p className="text-sm">{row.reason} · {row.archived_at}</p><button className="btn mt-2" disabled={busy||!data.can_archive} onClick={()=>{setSelected(row);setConfirmed(false);setReason('');}}>Revisar restauração</button></div>)}<div className="flex gap-3 mt-3"><button className="btn" disabled={busy||data.offset===0} onClick={()=>load(Math.max(0,data.offset-20))}>Anterior</button><button className="btn" disabled={busy||data.offset+20>=data.total} onClick={()=>load(data.offset+20)}>Próxima</button></div></>}{selected&&<div className="border-t mt-4 pt-4"><p>Restaurar <b>{selected.sku}</b> como rascunho; a aprovação anterior será removida.</p><label className="field mt-3">Motivo da restauração<textarea disabled={busy} maxLength={1000} value={reason} onChange={event=>{setReason(event.target.value);setConfirmed(false);}}/></label><label className="block text-sm my-3"><input type="checkbox" disabled={busy} checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/> Revisei este SKU e confirmo a restauração.</label><button className="btn" disabled={busy||!confirmed||reason.trim().length<5} onClick={restore}>Restaurar para nova preparação</button></div>}</section>;
}
