'use client';
import { useState } from 'react';
import Link from 'next/link';
import FeedRecovery from './FeedRecovery';
import FeedRetry from './FeedRetry';
import { api, download } from '../../lib/catalog/client';
import type { Channel } from '../../lib/catalog/channels';
type Props={selected:string[];channel:Channel;status:any;busy:boolean;run:(task:()=>Promise<void>)=>Promise<void>;refresh:()=>Promise<void>};
export default function BatchOperations({selected,channel,status,busy,run,refresh}:Props) {
  const [review,setReview]=useState<any>(null),[checked,setChecked]=useState<string[]>([]),[prepared,setPrepared]=useState<any>(null),[feeds,setFeeds]=useState<any[]>([]),[confirmed,setConfirmed]=useState(false),[results,setResults]=useState<any[]>([]);
  const loadFeeds=async()=>setFeeds((await api('/api/catalog/feed')).data);
  return <section className="card mt-5"><h2 className="text-lg font-bold">Revisão e publicação em lote</h2><p className="text-sm text-slate-500 mt-2">Revise conteúdo, fatos e pendências de cada item. A aprovação vale somente para a versão exibida.</p>
    <div className="flex flex-wrap gap-3 mt-4">
      <button className="btn" disabled={busy||!selected.length||selected.length>100} onClick={()=>run(async()=>{setReview({channel,items:(await api('/api/catalog/review',{channel,skus:selected})).items});setChecked([]);setResults([]);})}>Revisar seleção (até 100)</button>
      <button className="btn" disabled={busy||!selected.length||channel!=='amazon-us'} onClick={()=>run(async()=>{setPrepared({...await api('/api/catalog/feed',{skus:selected}),skus:[...selected]});setConfirmed(false);})}>Preparar feed Amazon</button>
      <button className="btn" disabled={busy||!status?.feeds} onClick={()=>run(loadFeeds)}>Consultar lotes enviados</button>
    </div>
    {review&&<div className="mt-4 space-y-3"><p className="font-bold">Revisão · {review.channel} · {review.items.length} itens</p>{review.items.map((item:any)=><details key={item.sku} className="rounded border p-3"><summary className="cursor-pointer">{item.sku} · {item.product.title} · {item.report.ready?'Pronto para revisão':`${item.report.issues.length} pendências`}</summary><Link className="text-blue-600 block my-2" href={`/catalog/${encodeURIComponent(item.sku)}?channel=${review.channel}`}>Abrir preparação completa</Link><p className="text-xs break-all">Versão: {item.updated_at} · {item.expected_hash}</p><pre className="text-xs whitespace-pre-wrap max-h-80 overflow-auto mt-3">{JSON.stringify(item.product,null,2)}</pre>{item.report.issues.map((issue:any,index:number)=><p key={index} className="text-sm text-red-700 mt-2">{issue.message} {issue.action}</p>)}<label className="flex gap-2 mt-3"><input type="checkbox" disabled={!item.report.ready||!status?.permissions?.review||busy} checked={checked.includes(item.sku)} onChange={event=>setChecked(event.target.checked?[...checked,item.sku]:checked.filter(sku=>sku!==item.sku))}/>Revisei este produto e aprovo esta versão</label></details>)}<button className="btn btn-primary" disabled={busy||!checked.length||!status?.permissions?.review} onClick={()=>run(async()=>{const entries=review.items.filter((item:any)=>checked.includes(item.sku)).map(({sku,expected_hash,updated_at}:any)=>({sku,expected_hash,updated_at}));setResults((await api('/api/catalog/review',{action:'approve',channel:review.channel,entries,confirm:true})).outcomes);setChecked([]);setReview(null);setPrepared(null);await refresh();})}>Registrar {checked.length} aprovações revisadas</button></div>}
    {results.length>0&&<div role="status" className="mt-3">{results.map(result=><p key={result.sku}>{result.sku} · {result.status} {result.error}</p>)}</div>}
    {prepared&&<div className="rounded border p-4 mt-4"><h3 className="font-bold">Manifesto Amazon · {prepared.manifest.length} produtos</h3><p className="text-xs break-all my-2">{prepared.manifest_hash}</p><details><summary>Revisar manifesto e conteúdo do envio</summary><pre className="text-xs whitespace-pre-wrap max-h-96 overflow-auto">{JSON.stringify({target:prepared.target,manifest:prepared.manifest,feed:prepared.feed},null,2)}</pre></details><button className="btn mt-3" onClick={()=>{download(prepared.feed,'amazon-listings-feed.json');download({target:prepared.target,manifest:prepared.manifest,manifest_hash:prepared.manifest_hash},'amazon-feed-manifest.json');}}>Baixar feed e manifesto</button><label className="flex gap-2 mt-3"><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>Revisei o manifesto e confirmo o envio à conta Amazon exibida</label><button className="btn btn-primary mt-3" disabled={busy||!confirmed||!status?.publication||!status?.feed_publication||!status?.permissions?.publish} onClick={()=>run(async()=>{await api('/api/catalog/feed',{action:'submit',skus:prepared.skus,expected_hash:prepared.manifest_hash,confirm:true,...(prepared.retry_of?{retry_of:prepared.retry_of}:{})});setPrepared(null);setConfirmed(false);await loadFeeds();await refresh();})}>Enviar feed revisado</button>{!status?.feed_publication&&<p className="text-sm text-amber-800 mt-2">Envio em lote ainda não foi habilitado para o piloto.</p>}</div>}
    {feeds.map(feed=><div key={feed.id} className="border-t mt-3 pt-3"><p>{feed.feed_id||'ID Amazon não confirmado'} · {feed.manifest.length} SKUs · {feed.status} · {feed.processing_status} · tentativa {feed.attempt_no}</p><p className="text-xs text-slate-500">{feed.created_at}</p><button className="btn mt-2" disabled={busy||!feed.feed_id||['completed','cancelled','failed'].includes(feed.status)} onClick={()=>run(async()=>{await api('/api/catalog/feed',{action:'monitor',id:feed.id});await loadFeeds();await refresh();})}>Consultar processamento e relatório</button><FeedRecovery feed={feed} canRecover={Boolean(status?.permissions?.publish)} busy={busy} run={run} reload={loadFeeds}/><FeedRetry feed={feed} busy={busy} canPrepare={Boolean(status?.permissions?.publish)} run={run} prepared={value=>{setPrepared(value);setConfirmed(false);}}/>{feed.status==='unknown'&&<p className="text-sm text-amber-800">Resultado incerto: investigue este lote antes de reenviar os produtos.</p>}</div>)}
  </section>;
}
