'use client';
import {useEffect,useState} from 'react';
import {api} from '../../lib/catalog/client';
export default function EbayRecovery({sku,busy,unsaved,canPublish,run,reload}:{sku:string;busy:boolean;unsaved:boolean;canPublish:boolean;run:(task:()=>Promise<void>)=>Promise<void>;reload:()=>Promise<void>}){
 const [report,setReport]=useState<any>(null),[offer,setOffer]=useState(''),[evidence,setEvidence]=useState(''),[confirmed,setConfirmed]=useState(false),[result,setResult]=useState<any>(null);
 useEffect(()=>{setReport(null);setOffer('');setEvidence('');setConfirmed(false);setResult(null);},[sku]);
 return <section className="card mt-5"><h2 className="font-bold text-lg">Investigar oferta eBay sem ID confirmado</h2><p className="text-sm text-slate-500 mt-2">Para um envio incerto após criar a oferta, consulte candidatos da mesma conta, SKU e conteúdo original. A associação exige evidência de gestão exclusiva. Ela preserva a incerteza até o readback e não publica a oferta.</p><button className="btn mt-3" disabled={busy||unsaved||!canPublish} onClick={()=>run(async()=>{setReport(await api('/api/catalog/ebay',{action:'recovery-candidates',sku}));setOffer('');setEvidence('');setConfirmed(false);setResult(null);})}>Consultar candidatos compatíveis</button>
 {report&&<div className="mt-3"><p className="text-sm">Conta {report.target.account_id} · {report.target.marketplace_id} · envio {report.claim_id}</p><details className="mt-3"><summary>Conferir o inventário e a oferta enviados originalmente</summary><pre className="text-xs whitespace-pre-wrap max-h-80 overflow-auto">{JSON.stringify(report.request_snapshot,null,2)}</pre></details>{!report.candidates.length?<p role="status" className="mt-3">Nenhuma oferta comprovada corresponde ao snapshot. Investigue no Seller Hub; a ausência não autoriza reenviar.</p>:<><label className="block mt-3">Oferta a associar<select className="border rounded p-2 ml-2" value={offer} onChange={event=>{setOffer(event.target.value);setConfirmed(false);}}><option value="">Selecione após investigar</option>{report.candidates.map((candidate:any)=><option key={candidate.offer_id} value={candidate.offer_id}>{candidate.offer_id} · {candidate.status}</option>)}</select></label><label className="block mt-3">Evidência da correspondência e da gestão exclusiva<textarea maxLength={2000} className="border rounded p-2 w-full" value={evidence} onChange={event=>{setEvidence(event.target.value);setConfirmed(false);}}/></label><label className="flex gap-2 mt-3"><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>Investiguei a conta e a oferta, conferi o conteúdo original e confirmo esta associação</label><button className="btn mt-3" disabled={busy||unsaved||!canPublish||!confirmed||!offer||evidence.trim().length<10} onClick={()=>run(async()=>{setResult(await api('/api/catalog/ebay',{action:'recover-offer',sku,claim_id:report.claim_id,expected_version:report.expected_version,offer_id:offer,evidence,confirm:true}));setReport(null);setConfirmed(false);await reload();})}>Associar ID e conservar envio incerto</button></>}</div>}
 {result&&<p role="status" className="mt-3">{result.message}</p>}
 </section>;
}
