'use client';
import {useState} from 'react';
import {api} from '../../lib/catalog/client';
type Props={sku?:string;status:any;busy:boolean;run:(task:()=>Promise<void>)=>Promise<void>};
export default function OfferOperations({sku,status,busy,run}:Props) {
  const [price,setPrice]=useState(true),[stock,setStock]=useState(false),[authority,setAuthority]=useState(false),[prepared,setPrepared]=useState<any>(null),[confirmed,setConfirmed]=useState(false),[result,setResult]=useState<any>(null);
  const reset=()=>{setPrepared(null);setConfirmed(false);};
  return <section className="card mt-5"><h2 className="font-bold text-lg">Atualizar oferta existente na Amazon</h2><p className="text-sm text-slate-500 mt-2">Selecione um produto aprovado. O envio atualiza somente os valores escolhidos; estoque exige FBM.</p><div className="flex flex-wrap gap-4 mt-3"><label><input type="checkbox" checked={price} onChange={event=>{setPrice(event.target.checked);reset();}}/> Preço</label><label><input type="checkbox" checked={stock} onChange={event=>{setStock(event.target.checked);reset();}}/> Estoque FBM</label></div><label className="flex gap-2 mt-3"><input type="checkbox" checked={authority} onChange={event=>{setAuthority(event.target.checked);reset();}}/>Confirmo que o PreListing é a fonte autorizada dos valores selecionados</label><button className="btn mt-3" disabled={busy||!sku||!authority||!price&&!stock} onClick={()=>run(async()=>{setPrepared({...await api('/api/catalog/offers',{sku,fields:[...(price?['price']:[]),...(stock?['qty']:[])],authority:'prelisting'}),fields:[...(price?['price']:[]),...(stock?['qty']:[])]});setConfirmed(false);setResult(null);})}>Preparar atualização de {sku||'um SKU selecionado'}</button>{prepared&&<div className="mt-3"><pre className="max-h-80 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(prepared,null,2)}</pre><label className="flex gap-2 mt-3"><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>Revisei o SKU, a conta e os valores e confirmo esta atualização</label><button className="btn btn-primary mt-3" disabled={busy||!confirmed||!status?.publication||!status?.offer_publication||!status?.permissions?.publish} onClick={()=>run(async()=>{setResult(await api('/api/catalog/offers',{action:'submit',sku:prepared.sku,fields:prepared.fields,authority:'prelisting',expected_hash:prepared.request_hash,confirm:true}));reset();})}>Enviar atualização revisada</button>{!status?.offer_publication&&<p className="text-sm text-amber-800 mt-2">Atualizações de oferta ainda não foram habilitadas para o piloto.</p>}</div>}{result&&<p role="status" className="mt-3">Resultado: {result.status}. Consulte o listing para verificar preço e disponibilidade.</p>}</section>;
}
