'use client';
import {useEffect,useState} from 'react';
import {api,download} from '../../lib/catalog/client';
type Props={sku:string;version:string;busy:boolean;unsaved:boolean;enabled:boolean;canPublish:boolean;run:(task:()=>Promise<void>)=>Promise<void>;reload:()=>Promise<void>};
export default function WalmartOperations({sku,version,busy,unsaved,enabled,canPublish,run,reload}:Props){
 const [prepared,setPrepared]=useState<any>(null),[confirmed,setConfirmed]=useState(false),[observation,setObservation]=useState<any>(null);
 useEffect(()=>{setPrepared(null);setConfirmed(false);setObservation(null);},[sku,version]);
 return <section className="card mt-5"><h2 className="font-bold text-lg">Walmart US · envio inicial de produto independente</h2><p className="text-sm mt-2">Get Spec completa, conta ativa e GTIN confirmado são necessários. A consulta mostra a ingestão; aceito não comprova publicação ou compra disponível.</p><div className="flex gap-2 mt-3"><button type="button" className="btn" disabled={busy||unsaved} onClick={()=>run(async()=>{setPrepared(await api('/api/catalog/walmart',{sku}));setConfirmed(false);})}>Preparar pacote e conferir conta</button><button type="button" className="btn" disabled={busy||unsaved} onClick={()=>run(async()=>{const response=await api('/api/catalog/walmart',{sku,action:'monitor'});await reload();setObservation(response.output);})}>Consultar ingestão Walmart</button></div>{prepared&&<div className="mt-4"><p>Conta {prepared.target.account_id} · {prepared.target.marketplace_id} · {prepared.request_hash}</p><details className="mt-3"><summary>Revisar manifesto e conteúdo</summary><pre className="text-xs whitespace-pre-wrap max-h-96 overflow-auto">{JSON.stringify(prepared,null,2)}</pre></details><button type="button" className="btn mt-3" disabled={busy||unsaved} onClick={()=>download(prepared,`${sku}-walmart-mp-item.json`)}>Baixar pacote e manifesto</button><label className="flex gap-2 mt-3"><input type="checkbox" disabled={busy||unsaved} checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>Revisei esta versão e confirmo a conta e a gestão exclusiva deste SKU</label><button type="button" className="btn mt-3" disabled={busy||unsaved||!enabled||!canPublish||!confirmed} onClick={()=>run(async()=>{await api('/api/catalog/walmart',{sku,action:'submit',confirm:true,expected_hash:prepared.request_hash});setPrepared(null);setConfirmed(false);})}>Enviar versão revisada</button>{!enabled&&<p className="text-sm text-amber-800 mt-2">Envio aguarda habilitação do piloto Walmart.</p>}</div>}{observation&&<pre role="status" className="text-xs whitespace-pre-wrap mt-3">{JSON.stringify(observation,null,2)}</pre>}</section>;
}
