'use client';
import {useEffect,useRef,useState} from 'react';

export default function Login() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const pending=useRef(false),errorRef=useRef<HTMLParagraphElement>(null);
  useEffect(()=>{if(error)errorRef.current?.focus();},[error]);
  return <main className="mx-auto max-w-md p-8 mt-16"><h1 className="text-3xl font-bold">FBR PreListing</h1><p className="mt-2 text-slate-500">Entre para preparar o catálogo e revisar as pendências.</p><form className="card mt-6 grid gap-4" aria-busy={busy} onSubmit={async event => { event.preventDefault(); if(pending.current)return;pending.current=true;setBusy(true); setError(''); try { const response = await fetch('/api/auth/session', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email, password }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error||'Falha ao entrar.'); window.location.href = '/catalog'; } catch (error) { setError(error instanceof Error ? error.message : 'Falha ao entrar.'); } finally { pending.current=false;setBusy(false); } }}><label className="field" htmlFor="login-email">Email<input id="login-email" type="email" autoComplete="username" required disabled={busy} value={email} onChange={event => setEmail(event.target.value)} /></label><label className="field" htmlFor="login-password">Senha<input id="login-password" type="password" autoComplete="current-password" required disabled={busy} value={password} onChange={event => setPassword(event.target.value)} /></label>{error && <p ref={errorRef} tabIndex={-1} role="alert" className="text-red-600">{error}</p>}<button type="submit" disabled={busy} className="btn btn-primary">{busy ? 'Entrando…' : 'Entrar'}</button><p role="status" aria-live="polite" className="text-sm">{busy?'Validando seu acesso…':''}</p></form></main>;
}
